### ISSUE TITLE
Set environment variable

### ISSUE THREAD

**Issue by m3brown** [m3brown/plz#18]
It would be nice if .plz.yaml could define environment variables for specific tasks. For example:

```yaml
- id: foobar
  env:
  - DJANGO_SETTINGS_MODULE=app.settings.dev
  cmd:
  - ./manage.py foo
  - ./manage.py bar
```

The current workaround is to wrap each cmd in a bash shell, which gets duplicative if there are multiple cmd steps

```yaml
- id: test
  cmd:
  - bash -c 'DJANGO_SETTINGS_MODULE=app.settings.dev ./manage.py foo'
  - bash -c 'DJANGO_SETTINGS_MODULE=app.settings.dev ./manage.py bar'
```
